version: '3.1'
services:
  python_db:
    image: mysql
    container_name:  "python_db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "DummySQL786"
      MYSQL_ROOT_USER: "root"
      MYSQL_PASSWORD: "DummySQL786"
      MYSQL_DATABASE: "py_db"
    ports:
      - "3308:3306"
    # once the db container's health is ready, then the go_api container will start. (order of execution : db -> go_api)
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 1s
      timeout: 3s
      retries: 20
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  python_api:
    container_name:  "python_api"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
    # we are depending on the mysql's container to be ready before running go_api.
    depends_on:       
      python_db:
        condition: service_healthy

    # connection docker container with host-port (of python).
    extra_hosts:
    - "host.docker.internal:host-gateway"
 
    volumes:
    # bind mount for file uploads - folder on host : folder on container
    - /home/g191387/Resumes:/app/Resumes

      # - /home/sarmad/Desktop/FYP_Resumes:/app/Resumes


